name: Deploy to Cloud Run from Source

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: "${{secrets.GCP_PROJECT_ID}}" # TODO: update Google Cloud project id
  SERVICE: cs3219-taskb4 # TODO: update Cloud Run service name
  REGION: asia-southeast1 # TODO: update Cloud Run service region

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Deploy a Cloud Function
        id: deploy-function
        uses: google-github-actions/deploy-cloud-functions@v0.1.0
        with:
          name: CS3219-TaskB-Serverless
          PROJECT_ID: "${{secrets.GCP_PROJECT_ID}}" # TODO: update Google Cloud project id
          runtime: nodejs10
          source_dir: src
          entry_point: serverlessFunction
