name: Deploy to Cloud Run from Source

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Delete Cloud Function
        run: gcloud functions delete CS3219-TaskB-Serverless --region=asia-southeast1

      - name: Deploy a Cloud Function
        run: gcloud functions deploy CS3219-TaskB-Serverless --entry-point serverless --runtime nodejs15 --trigger-http -project ${{secrets.GCP_PROJECT_ID}}
